const locationData = {
  "Hà Nội": {
    "Ba Đình": ["Phúc Xá", "Trúc Bạch", "Vĩnh Phúc"],
    "Cầu Giấy": ["Dịch Vọng", "Nghĩa Tân", "Mai Dịch"],
  },
};

const allProvinces = [
  "Hà Nội",
  "Hồ Chí Minh",
  "Hải Phòng",
  "Đà Nẵng",
  "Cần Thơ",
  "Tiền Giang",
  "Hậu Giang",
  "Đắk Nông",
  "Vĩnh Phúc",
  "Bắc Ninh",
  "Hải Dương",
  "Hưng Yên",
  "Hà Nam",
  "Nam Định",
  "Thái Bình",
  "Ninh Bình",
  "Hà Giang",
  "Cao Bằng",
  "Lào Cai",
  "Bắc Kạn",
  "Lạng Sơn",
  "Tuyên Quang",
  "Yên Bái",
  "Phú Thọ",
  "Bắc Giang",
  "Quảng Ninh",
  "Lai Châu",
  "Sơn La",
  "Hòa Bình",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thừa Thiên Huế",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Khánh Hòa",
  "Kon Tum",
  "Gia Lai",
  "Đắk Lắk",
  "Lâm Đồng",
  "Bình Phước",
  "Tây Ninh",
  "Bình Dương",
  "Đồng Nai",
  "Bình Thuận",
  "Bà Rịa - Vũng Tàu",
  "Long An",
  "An Giang",
  "Đồng Tháp",
  "Vĩnh Long",
  "Trà Vinh",
  "Bến Tre",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
];

export default locationData;
